from difflib import SequenceMatcher

def compare_script_versions(old_script: str, new_script: str) -> dict:
    """Compare two screenplay versions and return their line-level changes."""

    try:
        ##this checks if the inputs are strings and not empty, returning an error message if they are not valid
        if not isinstance(old_script, str) or not isinstance(new_script, str):
            return {
                "status": "error",
                "error_message": "Both screenplay versions must be text."
            }
        ##this checks if the inputs are empty strings, returning an error message if they are empty
        if not old_script.strip() or not new_script.strip():
            return {
                "status": "error",
                "error_message": "Both screenplay versions are required."
            }
        
        old_lines = old_script.splitlines()
        new_lines = new_script.splitlines()

        matcher = SequenceMatcher(
            None,
            old_lines,
            new_lines,
            autojunk=False 
        )

        changes = []

        ##this iterates through the opcodes generated by the SequenceMatcher, which represent the differences between the two scripts. For each change, it records the type of change (added, removed, modified), the lines from both scripts that were affected, and their respective line ranges.
        for tag, old_start, old_end, new_start, new_end in matcher.get_opcodes():
            if tag == "equal":
                continue

            changes.append({
                "change_type": tag,
                "old_lines": old_lines[old_start:old_end],
                "new_lines": new_lines[new_start:new_end],
                "old_line_range": [old_start + 1, old_end],
                "new_line_range": [new_start + 1, new_end],
            })

        return {
            "status": "success",
            "total_changes": len(changes),
            "changes": changes,
        }

    except Exception:
        return {
            "status": "error",
            "error_message": "The screenplay comparison failed."
        }